Improved: CircleCI builds are more efficient
 - master branch and new branches are always built from scratch.
 - Existing branches cache their built documentation & reuse that to only
 rebuild any differences.
 - The cahce is purged daily, hence the first push of the day is rebuilt from
 scratch.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,7 +1,12 @@
+# quick-build rebuilds changes using the cached documentation.
+# The cache is emptied everyday, forcing a full build on the day's first push.
+# It doesn't operate on master branch. New branches are always built from scratch.
+# full-build always rebuilds from scratch, without any cache. Only for changes in master branch.
+
 version: 2
 
 jobs:
-  build:
+  quick-build:
     docker:
       - image: circleci/python:3.6
     environment:
@@ -23,14 +28,86 @@ jobs:
         # Installing required packages for `make -C doc check command` to work.
       - run: sudo -E apt-get -yq update
       - run: sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install dvipng texlive-latex-base texlive-latex-extra
+      - run:
+          name: Generating today's date and writing to file to generate daily new cache key
+          command: |
+            date +%F > today
       - restore_cache:
-          key: v1-packages+datasets-{{ .Branch }}
-      - run: wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
-      - run: chmod +x ~/miniconda.sh && ~/miniconda.sh -b
+          key: v5-packages+datasets-{{ .Branch }}-{{ checksum "today" }}
+      - run:
+          name: Download & install conda if absent
+          command: |
+            if
+              ls $HOME/miniconda3/bin | grep conda -q
+            then
+              echo "(Mini)Conda already present from the cache."
+            else
+              wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
+              chmod +x ~/miniconda.sh && ~/miniconda.sh -b
+            fi
       - run:
           name: Setup conda path in env variables
           command: |
             echo 'export PATH="$HOME/miniconda3/bin:$PATH"'  >> $BASH_ENV
+      - run:
+          name: Create new conda env  # Separate command so if it fails (when using cache) the entire build will not.
+          command: |
+            if conda env list | grep testenv ; then echo "Conda env testenv already exists courtesy of the cache."; else conda create -n testenv -yq; fi
+      - run:
+          name: Install packages in conda env
+          command: |
+            conda install -n testenv python=3.6 numpy scipy scikit-learn matplotlib pandas \
+            flake8 lxml nose cython mkl sphinx coverage patsy boto3 pillow pandas -yq
+            conda install -n testenv nibabel nilearn nose-timer -c conda-forge -yq
+      - run:
+          name: Running CircleCI test (make html)
+          command: |
+            source activate testenv
+            pip install -e .
+            set -o pipefail && cd doc && make html 2>&1 | tee ~/log.txt
+          no_output_timeout: 5h
+      - save_cache:
+          key: v5-packages+datasets-{{ .Branch }}-{{ checksum "today" }}
+          paths:
+          - ../nilearn_data
+          - ../miniconda3
+          - doc
+
+      - store_artifacts:
+          path: doc/_build/html
+      - store_artifacts:
+          path: coverage
+      - store_artifacts:
+          path: $HOME/log.txt
+          destination: log.txt
+
+
+
+  full-build:
+    docker:
+      - image: circleci/python:3.6
+    environment:
+      DISTRIB: "conda"
+      PYTHON_VERSION: "3.6"
+      NUMPY_VERSION: "*"
+      SCIPY_VERSION: "*"
+      SCIKIT_LEARN_VERSION: "*"
+      MATPLOTLIB_VERSION: "*"
+
+    steps:
+      - checkout
+        # Get rid of existing virtualenvs on circle ci as they conflict with conda.
+        # Trick found here:
+        # https://discuss.circleci.com/t/disable-autodetection-of-project-or-application-of-python-venv/235/10
+      - run: cd && rm -rf ~/.pyenv && rm -rf ~/virtualenvs
+        # We need to remove conflicting texlive packages.
+      - run: sudo -E apt-get -yq remove texlive-binaries --purge
+        # Installing required packages for `make -C doc check command` to work.
+      - run: sudo -E apt-get -yq update
+      - run: sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install dvipng texlive-latex-base texlive-latex-extra
+      - run: wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
+      - run: chmod +x ~/miniconda.sh && ~/miniconda.sh -b
+      - run: echo 'export PATH="$HOME/miniconda3/bin:$PATH"'  >> $BASH_ENV
       - run:
           name: Create conda env
           command: |
@@ -44,11 +121,6 @@ jobs:
             pip install -e .
             set -o pipefail && cd doc && make html 2>&1 | tee ~/log.txt
           no_output_timeout: 5h
-      - save_cache:
-          key: v1-packages+datasets-{{ .Branch }}
-          paths:
-          - $HOME/nilearn_data
-          - $HOME/miniconda3
 
       - store_artifacts:
           path: doc/_build/html
@@ -57,3 +129,22 @@ jobs:
       - store_artifacts:
           path: $HOME/log.txt
           destination: log.txt
+
+
+workflows:
+  version: 2
+  push:
+    jobs:
+      - quick-build:
+          filters:
+            branches:
+              ignore:
+                - master
+                - test-circleci
+
+      - full-build:
+          filters:
+            branches:
+              only:
+                - master
+                - test-circleci
