fix

diff --git a/.github/workflows/test_with_free_threaded_python.yml b/.github/workflows/test_with_free_threaded_python.yml
--- a/.github/workflows/test_with_free_threaded_python.yml
+++ b/.github/workflows/test_with_free_threaded_python.yml
@@ -34,64 +34,64 @@ env:
     FORCE_COLOR: true
 
 jobs:
-    test_and_coverage:
-        if: github.repository == 'nilearn/nilearn'
-        name: 'Test with ${{ matrix.py }} on ${{ matrix.os }}: ${{ matrix.description }}'
-        runs-on: ${{ matrix.os }}
-        strategy:
-            fail-fast: true
-            matrix:
-                description: [latest dependencies]
-                py: [3.14t]
-                os: [ubuntu-latest, macos-latest, windows-latest]
-                env: [free_threaded]
-        steps:
-        -   uses: actions/checkout@v6
-        -   name: Install the latest version of uv
-            uses: astral-sh/setup-uv@v7
-        -   name: Setup python
-            uses: actions/setup-python@v6
-            with:
-                python-version: ${{ matrix.py }}
-                allow-prereleases: true
-        -   name: Install tox
-            run: uv tool install tox --with=tox-uv --with=tox-gh-actions
-        -   name: Show tox config
-            run: tox c
-        -   name: Run test suite
-            id: test_free_threaded
-            run: |
-                tox run --list-dependencies -e ${{ matrix.env }} -- nilearn
-                tox run -e plot_test_timing
-        -   name: Upload test report
-            if: success() || failure()
-            uses: actions/upload-artifact@v5
-            with:
-                name: ${{ matrix.os }}_${{ matrix.py }}_${{ matrix.description }}_report.html
-                path: report.html
-        -   name: Upload test timings
-            if: success() || failure()
-            uses: actions/upload-artifact@v5
-            with:
-                name: ${{ matrix.os }}_${{ matrix.py }}_${{ matrix.description }}_pytest_output
-                path: results/pytest_output
+    # test_and_coverage:
+    #     if: github.repository == 'nilearn/nilearn'
+    #     name: 'Test with ${{ matrix.py }} on ${{ matrix.os }}: ${{ matrix.description }}'
+    #     runs-on: ${{ matrix.os }}
+    #     strategy:
+    #         fail-fast: true
+    #         matrix:
+    #             description: [latest dependencies]
+    #             py: [3.14t]
+    #             os: [ubuntu-latest, macos-latest, windows-latest]
+    #             env: [free_threaded]
+    #     steps:
+    #     -   uses: actions/checkout@v6
+    #     -   name: Install the latest version of uv
+    #         uses: astral-sh/setup-uv@v7
+    #     -   name: Setup python
+    #         uses: actions/setup-python@v6
+    #         with:
+    #             python-version: ${{ matrix.py }}
+    #             allow-prereleases: true
+    #     -   name: Install tox
+    #         run: uv tool install tox --with=tox-uv --with=tox-gh-actions
+    #     -   name: Show tox config
+    #         run: tox c
+    #     -   name: Run test suite
+    #         id: test_free_threaded
+    #         run: |
+    #             tox run --list-dependencies -e ${{ matrix.env }} -- nilearn
+    #             tox run -e plot_test_timing
+    #     -   name: Upload test report
+    #         if: success() || failure()
+    #         uses: actions/upload-artifact@v5
+    #         with:
+    #             name: ${{ matrix.os }}_${{ matrix.py }}_${{ matrix.description }}_report.html
+    #             path: report.html
+    #     -   name: Upload test timings
+    #         if: success() || failure()
+    #         uses: actions/upload-artifact@v5
+    #         with:
+    #             name: ${{ matrix.os }}_${{ matrix.py }}_${{ matrix.description }}_pytest_output
+    #             path: results/pytest_output
 
-        -   name: Create issue
-            if: ${{ steps.test_free_threaded.outcome != 'success' }}
-            uses: JasonEtco/create-an-issue@v2.9.2
-            env:
-                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-                run_id: ${{ github.run_id }}
-                repository: ${{ github.repository }}
-                workflow_name: TEST FREE THREADED PYTHON
-            with:
-                filename: .github/workflow_failure.md
-                update_existing: true
-                search_existing: open
+    #     -   name: Create issue
+    #         if: ${{ steps.test_free_threaded.outcome != 'success' }}
+    #         uses: JasonEtco/create-an-issue@v2.9.2
+    #         env:
+    #             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    #             run_id: ${{ github.run_id }}
+    #             repository: ${{ github.repository }}
+    #             workflow_name: TEST FREE THREADED PYTHON
+    #         with:
+    #             filename: .github/workflow_failure.md
+    #             update_existing: true
+    #             search_existing: open
 
-        -   name: Return failure
-            if: ${{ steps.test_free_threaded.outcome != 'success' }}
-            run: exit 1
+    #     -   name: Return failure
+    #         if: ${{ steps.test_free_threaded.outcome != 'success' }}
+    #         run: exit 1
 
 
     free_threaded:
